[2025-10-08T05:59:44.667+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: inventory_analytics_pipeline.create_inventory_table scheduled__2025-10-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
